"""Parity test for intent-token signature verification.

Vector generated by the Python IAP signer (Ed25519 over canonical JSON);
includes a non-ASCII char and floats to exercise canonicalization.
"""

from armoriq_sdk.crypto_verify import canonical_json, verify_ed25519

PAYLOAD = {
    "plan_hash": "abc123",
    "issued_at": 1700000000.5,
    "expires_at": 1700000060.5,
    "policy": {"allowed_tools": ["search", "réad"], "deny": []},
    "identity": "agent@armoriq.io",
    "public_key": "e23dbe8dbb842eef51a8d7dba01019814e5e6eaa29936fe5aca3570b78bbd5f8",
    "version": "1.0",
}
PUBLIC_KEY = "e23dbe8dbb842eef51a8d7dba01019814e5e6eaa29936fe5aca3570b78bbd5f8"
SIGNATURE = (
    "61c5a5169165d208fa3486b72262b5f0f9ae3c1f473379f9d6b729c2a3d6eb6c"
    "244caf14814b3e81930fed867f4f832eed5421ecd6db525428c92416b9818307"
)
PY_CANONICAL = (
    '{"expires_at":1700000060.5,"identity":"agent@armoriq.io",'
    '"issued_at":1700000000.5,"plan_hash":"abc123",'
    '"policy":{"allowed_tools":["search","r\\u00e9ad"],"deny":[]},'
    '"public_key":"e23dbe8dbb842eef51a8d7dba01019814e5e6eaa29936fe5aca3570b78bbd5f8",'
    '"version":"1.0"}'
)


def test_canonical_json_matches_signer():
    assert canonical_json(PAYLOAD).decode() == PY_CANONICAL


def test_verify_genuine_signature():
    assert verify_ed25519(PUBLIC_KEY, canonical_json(PAYLOAD), SIGNATURE) is True


def test_verify_rejects_tampered_plan_hash():
    tampered = {**PAYLOAD, "plan_hash": "deadbeef"}
    assert verify_ed25519(PUBLIC_KEY, canonical_json(tampered), SIGNATURE) is False


def test_verify_rejects_malformed_inputs():
    assert verify_ed25519("00", b"x", SIGNATURE) is False
    assert verify_ed25519(PUBLIC_KEY, b"x", "ab") is False
